# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('mailUser', models.CharField(max_length=45)),
                ('passwordUser', models.CharField(max_length=20)),
                ('createAt', models.DateTimeField()),
                ('updateAt', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
