# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('idUser', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('default', models.CharField(max_length=40)),
                ('current', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('idUserProfile', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('picture01', models.CharField(max_length=200, null=True)),
                ('picture02', models.CharField(max_length=200, null=True)),
                ('picture03', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('idUser', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nameUserProfile', models.CharField(max_length=20)),
                ('genderUserProfile', models.SmallIntegerField()),
                ('ageUserProfile', models.CharField(max_length=2)),
                ('statusUserProfile', models.CharField(max_length=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('idUser', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('mailUser', models.CharField(max_length=45)),
                ('passwordUser', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('token_push', models.CharField(max_length=100)),
                ('City_idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
                ('Pictures_idUserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Pictures')),
                ('UserProfile_idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
            ],
        ),
    ]
