# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171121_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='token_push',
            field=models.CharField(default='something', max_length=100),
        ),
    ]
