# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_users_token_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='token_push',
            field=models.CharField(max_length=100),
        ),
    ]
