# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171121_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nameUser',
            field=models.CharField(default='thallyssonklein', max_length=20),
        ),
    ]
