# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_users_nameuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
