# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20171122_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updateAt',
        ),
    ]
